[2024-06-04T12:26:07.109+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T12:26:07.140+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_test_weather.load_weather_data manual__2024-06-04T12:25:34.133361+00:00 [queued]>
[2024-06-04T12:26:07.158+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_test_weather.load_weather_data manual__2024-06-04T12:25:34.133361+00:00 [queued]>
[2024-06-04T12:26:07.160+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T12:26:07.196+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_weather_data> on 2024-06-04 12:25:34.133361+00:00
[2024-06-04T12:26:07.213+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=138) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T12:26:07.218+0000] {standard_task_runner.py:63} INFO - Started process 141 to run task
[2024-06-04T12:26:07.219+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_test_weather', 'load_weather_data', 'manual__2024-06-04T12:25:34.133361+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_extraction_test_weather.py', '--cfg-path', '/tmp/tmpglz0a1pe']
[2024-06-04T12:26:07.226+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask load_weather_data
[2024-06-04T12:26:07.406+0000] {task_command.py:426} INFO - Running <TaskInstance: data_extraction_test_weather.load_weather_data manual__2024-06-04T12:25:34.133361+00:00 [running]> on host cb1b576ccea9
[2024-06-04T12:26:07.565+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matheus' AIRFLOW_CTX_DAG_ID='data_extraction_test_weather' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T12:25:34.133361+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T12:25:34.133361+00:00'
[2024-06-04T12:26:07.569+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T12:26:07.682+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-04T12:26:07.683+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T12:26:07.702+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_extraction_test_weather, task_id=load_weather_data, run_id=manual__2024-06-04T12:25:34.133361+00:00, execution_date=20240604T122534, start_date=20240604T122607, end_date=20240604T122607
[2024-06-04T12:26:07.759+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T12:26:07.791+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-04T12:26:07.794+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
