[2024-06-04T12:48:07.602+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T12:48:07.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_extraction_test_weather.load_weather_data manual__2024-06-04T12:47:26.828542+00:00 [queued]>
[2024-06-04T12:48:07.689+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_extraction_test_weather.load_weather_data manual__2024-06-04T12:47:26.828542+00:00 [queued]>
[2024-06-04T12:48:07.692+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T12:48:07.756+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_weather_data> on 2024-06-04 12:47:26.828542+00:00
[2024-06-04T12:48:07.786+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T12:48:07.795+0000] {standard_task_runner.py:63} INFO - Started process 129 to run task
[2024-06-04T12:48:07.796+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_test_weather', 'load_weather_data', 'manual__2024-06-04T12:47:26.828542+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_extraction_test_weather.py', '--cfg-path', '/tmp/tmpb3wu08eq']
[2024-06-04T12:48:07.814+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask load_weather_data
[2024-06-04T12:48:08.047+0000] {task_command.py:426} INFO - Running <TaskInstance: data_extraction_test_weather.load_weather_data manual__2024-06-04T12:47:26.828542+00:00 [running]> on host 6b740a15ab9e
[2024-06-04T12:48:08.429+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matheus' AIRFLOW_CTX_DAG_ID='data_extraction_test_weather' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T12:47:26.828542+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T12:47:26.828542+00:00'
[2024-06-04T12:48:08.434+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T12:48:08.534+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-04T12:48:08.535+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T12:48:08.565+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_extraction_test_weather, task_id=load_weather_data, run_id=manual__2024-06-04T12:47:26.828542+00:00, execution_date=20240604T124726, start_date=20240604T124807, end_date=20240604T124808
[2024-06-04T12:48:08.613+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T12:48:08.670+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-04T12:48:08.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
