[2024-06-04T12:48:45.009+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T12:48:45.045+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_directions.directions_api_ready manual__2024-06-04T12:48:41.445735+00:00 [queued]>
[2024-06-04T12:48:45.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_directions.directions_api_ready manual__2024-06-04T12:48:41.445735+00:00 [queued]>
[2024-06-04T12:48:45.064+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T12:48:45.100+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): directions_api_ready> on 2024-06-04 12:48:41.445735+00:00
[2024-06-04T12:48:45.109+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=138) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T12:48:45.113+0000] {standard_task_runner.py:63} INFO - Started process 142 to run task
[2024-06-04T12:48:45.113+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_directions', 'directions_api_ready', 'manual__2024-06-04T12:48:41.445735+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/test_directions.py', '--cfg-path', '/tmp/tmpfmc2dule']
[2024-06-04T12:48:45.117+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask directions_api_ready
[2024-06-04T12:48:45.211+0000] {task_command.py:426} INFO - Running <TaskInstance: test_directions.directions_api_ready manual__2024-06-04T12:48:41.445735+00:00 [running]> on host 6b740a15ab9e
[2024-06-04T12:48:45.409+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matheus' AIRFLOW_CTX_DAG_ID='test_directions' AIRFLOW_CTX_TASK_ID='directions_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T12:48:41.445735+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T12:48:41.445735+00:00'
[2024-06-04T12:48:45.412+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T12:48:45.413+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-06-04T12:48:45.414+0000] {http.py:137} INFO - Poking: /maps/api/directions/json?destination=Brasilia&origin=Juiz-de-fora&key=AIzaSyCRlfIDXyWr4l29C6pJJIhkxXGS44vI0qw
[2024-06-04T12:48:45.431+0000] {base.py:84} INFO - Using connection ID 'directions_api' for task execution.
[2024-06-04T12:48:46.460+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-04T12:48:46.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T12:48:46.493+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_directions, task_id=directions_api_ready, run_id=manual__2024-06-04T12:48:41.445735+00:00, execution_date=20240604T124841, start_date=20240604T124845, end_date=20240604T124846
[2024-06-04T12:48:46.580+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T12:48:46.612+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
