[2024-06-04T18:21:57.003+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T18:21:57.034+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL_weather.transform_load_weather_data manual__2024-06-04T18:21:33.739279+00:00 [queued]>
[2024-06-04T18:21:57.054+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL_weather.transform_load_weather_data manual__2024-06-04T18:21:33.739279+00:00 [queued]>
[2024-06-04T18:21:57.057+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-04T18:21:57.091+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-06-04 18:21:33.739279+00:00
[2024-06-04T18:21:57.107+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=368) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T18:21:57.111+0000] {standard_task_runner.py:63} INFO - Started process 370 to run task
[2024-06-04T18:21:57.112+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL_weather', 'transform_load_weather_data', 'manual__2024-06-04T18:21:33.739279+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/dag_ETL_weather.py', '--cfg-path', '/tmp/tmpluo7cj8q']
[2024-06-04T18:21:57.115+0000] {standard_task_runner.py:91} INFO - Job 114: Subtask transform_load_weather_data
[2024-06-04T18:21:57.243+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL_weather.transform_load_weather_data manual__2024-06-04T18:21:33.739279+00:00 [running]> on host 6b740a15ab9e
[2024-06-04T18:21:57.392+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matheus' AIRFLOW_CTX_DAG_ID='dag_ETL_weather' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T18:21:33.739279+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T18:21:33.739279+00:00'
[2024-06-04T18:21:57.396+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T18:21:57.453+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-04T18:21:57.613+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-04T18:21:57.691+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-04T18:21:57.693+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T18:21:57.706+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_ETL_weather, task_id=transform_load_weather_data, run_id=manual__2024-06-04T18:21:33.739279+00:00, execution_date=20240604T182133, start_date=20240604T182157, end_date=20240604T182157
[2024-06-04T18:21:57.770+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T18:21:57.805+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-04T18:21:57.809+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
